name: Publish Container Image to GCP Artifact Registry

on:
  push:
    branches:
      - "master"
    tags:
      - "**"

jobs:
  build-push-registry:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: "${{ secrets.PROJECT_ID }}"
      REPOSITORY: container-images
      IMAGE: website
      REGION: europe-west3-docker.pkg.dev

    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGION }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"
      - uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker $REGION --quiet

      - name: Build and Push Docker Image to Artifact Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
